import { AccessoryIcon, EyeIcon, FaceIcon, HairIcon, PantsIcon, ShirtIcon, ShoeIcon, SparkIcon } from "@/components/atoms/icons";
import { LayerSelector } from "@/components/molecules/LayerSelector";
import { MANA_SEED_FREE } from "@/data/mana-seed";
import type { BodyType, ManaSeedAppearance } from "@/types/character";

export function CharacterLayersPanel({ name, bodyType, appearance, onNameChange, onBodyTypeChange, onRotate, onHeadwearChange }: { name: string; bodyType: BodyType; appearance: ManaSeedAppearance; onNameChange: (value: string) => void; onBodyTypeChange: (value: BodyType) => void; onRotate: (part: keyof ManaSeedAppearance, direction: -1 | 1) => void; onHeadwearChange: (value: ManaSeedAppearance["headwear"]) => void }) {
  const hairs = Object.keys(MANA_SEED_FREE.hairstyles) as ManaSeedAppearance["hair"][];
  const shirts = Object.keys(MANA_SEED_FREE.shirts) as ManaSeedAppearance["shirt"][];
  return <section className="creator-ornate-panel p-4 sm:p-5" aria-label="Seletores de camadas"><header className="creator-panel-heading"><span>✦</span><div><p>CRIAR SEU HERÓI</p><small>CAMADAS DO SPRITE</small></div><span>✦</span></header><label className="mt-5 block"><span className="creator-mini-heading">NOME DO HERÓI</span><input value={name} maxLength={18} onChange={(event) => onNameChange(event.target.value)} className="creator-parchment-input mt-2" /></label><div className="mt-4 flex items-center gap-3"><span className="creator-mini-heading">BASE</span>{(["hero", "heroine"] as const).map((type) => <button key={type} type="button" onClick={() => onBodyTypeChange(type)} aria-label={type === "hero" ? "Base de herói" : "Base de heroína"} className={`creator-gender-button ${bodyType === type ? "creator-gender-button--active" : ""}`}>{type === "hero" ? "♂" : "♀"}</button>)}<small className="text-[9px] font-bold text-[#876841]">Base disponível: humano</small></div><div className="mt-5 grid gap-2"><LayerSelector label="Tom de pele" value="Natural" count="1/1" icon={FaceIcon} /><LayerSelector label="Estilo do cabelo" value={MANA_SEED_FREE.hairstyles[appearance.hair].label} count={`${hairs.indexOf(appearance.hair) + 1}/${hairs.length}`} icon={HairIcon} enabled onPrevious={() => onRotate("hair", -1)} onNext={() => onRotate("hair", 1)} /><LayerSelector label="Cor do cabelo" value="Original" count="1/1" icon={HairIcon} /><LayerSelector label="Cor dos olhos" value="Natural" count="1/1" icon={EyeIcon} /><LayerSelector label="Camisa" value={MANA_SEED_FREE.shirts[appearance.shirt].label} count={`${shirts.indexOf(appearance.shirt) + 1}/${shirts.length}`} icon={ShirtIcon} enabled onPrevious={() => onRotate("shirt", -1)} onNext={() => onRotate("shirt", 1)} /><LayerSelector label="Calça" value="Calça longa" count="1/1" icon={PantsIcon} /></div><div className="mt-5 border-t-2 border-[#756142] pt-4"><p className="creator-mini-heading">EXTRAS / ACESSÓRIOS</p><div className="mt-3 grid grid-cols-4 gap-2"><button type="button" onClick={() => onHeadwearChange("none")} className={`creator-accessory ${appearance.headwear === "none" ? "creator-accessory--active" : ""}`} title="Sem acessório">×</button><button type="button" onClick={() => onHeadwearChange("cowboyHat")} className={`creator-accessory ${appearance.headwear === "cowboyHat" ? "creator-accessory--active" : ""}`} title="Chapéu cowboy"><AccessoryIcon className="h-5 w-5" /></button><button type="button" disabled className="creator-accessory" title="Indisponível na amostra"><SparkIcon className="h-5 w-5" /></button><button type="button" disabled className="creator-accessory" title="Indisponível na amostra"><ShoeIcon className="h-5 w-5" /></button></div></div></section>;
}
