import { FaceIcon, PantsIcon, ShirtIcon, ShoeIcon } from "@/components/atoms/icons";
import Image from "next/image";
import { CHARACTER_AURAS, CHARACTER_PRESETS } from "@/data/character-options";
import type { CharacterAura, CharacterPreset } from "@/types/character";

const icons = { shirt: ShirtIcon, face: FaceIcon, shoe: ShoeIcon, pants: PantsIcon };

export function CharacterPresetPanel({ activePreset, aura, onPreset, onAura }: { activePreset: string; aura: CharacterAura; onPreset: (preset: CharacterPreset) => void; onAura: (aura: CharacterAura) => void }) {
  return <section className="creator-ornate-panel p-4 sm:p-5" aria-label="Pre-sets de traje e classe"><header className="creator-panel-heading"><span>✦</span><div><p>PRE-SETS</p><small>TRAJES DO HERÓI</small></div><span>✦</span></header><p className="creator-panel-note mt-4">Escolha um conjunto para equipar o aventureiro de uma vez.</p><div className="mt-4 grid grid-cols-2 gap-3">{CHARACTER_PRESETS.map((preset) => { const Icon = icons[preset.icon]; return <button type="button" key={preset.id} onClick={() => onPreset(preset)} className={`creator-preset ${activePreset === preset.id ? "creator-preset--active" : ""}`}><span className="creator-preset-icon"><Icon className="h-7 w-7" /></span><strong className="mt-2 block text-[10px] uppercase tracking-wide">{preset.label}</strong><small className="mt-1 block text-[8px] leading-tight opacity-75">{preset.helper}</small></button>; })}</div><div className="mt-6 border-t-2 border-[#756142] pt-5"><p className="creator-mini-heading">ESCOLHA SUA CLASSE</p><div className="mt-3 grid grid-cols-3 gap-2">{CHARACTER_AURAS.map((option) => <button type="button" key={option.name} title={option.name} aria-label={`Classe ${option.name}`} onClick={() => onAura(option)} className={`creator-aura-option ${aura.name === option.name ? "creator-aura-option--active" : ""}`}><Image src={option.image} alt="" width={512} height={512} className="creator-class-image" /><small>{option.name}</small></button>)}</div><p className="mt-3 text-center text-[9px] font-black uppercase tracking-wider text-[#d5bd8a]">Classe ativa: {aura.name}</p></div><aside className="mt-5 creator-free-note">O pacote atual fornece 2 cabelos, 2 camisas e 1 acessório. Novas camadas surgem quando houver novos sprites.</aside></section>;
}
