import { ChevronIcon, ScrollIcon } from "@/components/atoms/icons";
import { QuestLoader } from "@/components/atoms/QuestLoader";
import { StateMessage } from "@/components/atoms/StateMessage";
import type { EvidenceSubmission } from "@/types/moderation";
import { formatDate } from "@/utils/format-date";

export function EvidenceQueue({ evidences, loading, onOpen }: { evidences: EvidenceSubmission[]; loading: boolean; onOpen: (id: string) => void }) {
  if (loading) return <QuestLoader label="Buscando evidências pendentes..." />;
  if (!evidences.length) return <StateMessage icon={<ScrollIcon className="mx-auto mb-3 h-8 w-8 text-[#71552b]" />}><strong className="block text-sm text-[#d7c5a0]">Nenhuma pendência encontrada</strong><span className="mt-1 block text-xs text-[#878174]">Ajuste ou limpe os filtros para consultar a fila completa.</span></StateMessage>;
  return <div><header className="hidden grid-cols-[1.1fr_1.25fr_.8fr_.8fr_auto] gap-4 border-b-2 border-[#4d391b] bg-[#12130f] px-7 py-4 text-[10px] font-black uppercase tracking-wider text-[#9d947e] md:grid"><span>Colaborador</span><span>Missão</span><span>Evidência</span><span>Submetida em</span><span>Status</span></header>{evidences.map((evidence) => <button key={evidence.id} onClick={() => onOpen(evidence.id)} className="group grid w-full gap-4 border-b-2 border-[#302a1b] px-5 py-5 text-left transition last:border-b-0 hover:bg-[#1c1a10] focus:bg-[#1c1a10] focus:outline-none md:grid-cols-[1.1fr_1.25fr_.8fr_.8fr_auto] md:items-center md:px-7"><span className="flex items-center gap-3"><span className="grid h-9 w-9 shrink-0 place-items-center border-2 border-[#76521e] bg-[#292010] text-[10px] font-black text-gold-light">{evidence.collaborator.initials}</span><span><strong className="block text-sm text-[#ebdbb8]">{evidence.collaborator.name}</strong><small className="mt-1 block text-[10px] text-[#7e796c] md:hidden">{evidence.missionTitle}</small></span></span><span className="hidden text-xs font-bold text-[#c3bca8] md:block">{evidence.missionTitle}</span><span className="text-xs text-[#aaa18c]">{evidence.evidenceType}</span><time className="text-xs text-[#9d9787]">{formatDate(evidence.submittedAt)}</time><span className="flex items-center justify-between gap-3"><strong className="border-2 border-[#876125] bg-[#30230f] px-2 py-1 text-[9px] uppercase tracking-wider text-gold-light">{evidence.status}</strong><ChevronIcon className="h-4 w-4 text-[#987235] transition group-hover:translate-x-1 group-hover:text-gold-light" /></span></button>)}</div>;
}
