FROM golang:1.24-alpine AS build

ARG MINIO_RELEASE=RELEASE.2025-04-22T22-12-26Z

RUN go install "github.com/minio/minio@${MINIO_RELEASE}"

FROM alpine:3.20

COPY --from=build /go/bin/minio /usr/local/bin/minio

ENTRYPOINT ["/usr/local/bin/minio"]
