/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './pages/__root'
import { Route as AppLayoutRouteImport } from './pages/_app/layout'
import { Route as AppIndexRouteImport } from './pages/_app/index'
import { Route as AppCharactersIndexRouteImport } from './pages/_app/characters/index'
import { Route as AppMissionsIndexRouteImport } from './pages/_app/missions/index'
import { Route as AppModerationIndexRouteImport } from './pages/_app/moderation/index'
import { Route as AppPerfilIndexRouteImport } from './pages/_app/perfil/index'
import { Route as AppRankingIndexRouteImport } from './pages/_app/ranking/index'
import { Route as AppMissionsNewIndexRouteImport } from './pages/_app/missions/new/index'
import { Route as AppModerationIdIndexRouteImport } from './pages/_app/moderation/$id/index'
import { Route as AppMissionsIdEditIndexRouteImport } from './pages/_app/missions/$id/edit/index'

const AppLayoutRoute = AppLayoutRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppLayoutRoute,
} as any)
const AppCharactersIndexRoute = AppCharactersIndexRouteImport.update({
  id: '/characters/',
  path: '/characters/',
  getParentRoute: () => AppLayoutRoute,
} as any)
const AppMissionsIndexRoute = AppMissionsIndexRouteImport.update({
  id: '/missions/',
  path: '/missions/',
  getParentRoute: () => AppLayoutRoute,
} as any)
const AppModerationIndexRoute = AppModerationIndexRouteImport.update({
  id: '/moderation/',
  path: '/moderation/',
  getParentRoute: () => AppLayoutRoute,
} as any)
const AppPerfilIndexRoute = AppPerfilIndexRouteImport.update({
  id: '/perfil/',
  path: '/perfil/',
  getParentRoute: () => AppLayoutRoute,
} as any)
const AppRankingIndexRoute = AppRankingIndexRouteImport.update({
  id: '/ranking/',
  path: '/ranking/',
  getParentRoute: () => AppLayoutRoute,
} as any)
const AppMissionsNewIndexRoute = AppMissionsNewIndexRouteImport.update({
  id: '/missions/new/',
  path: '/missions/new/',
  getParentRoute: () => AppLayoutRoute,
} as any)
const AppModerationIdIndexRoute = AppModerationIdIndexRouteImport.update({
  id: '/moderation/$id/',
  path: '/moderation/$id/',
  getParentRoute: () => AppLayoutRoute,
} as any)
const AppMissionsIdEditIndexRoute = AppMissionsIdEditIndexRouteImport.update({
  id: '/missions/$id/edit/',
  path: '/missions/$id/edit/',
  getParentRoute: () => AppLayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/characters/': typeof AppCharactersIndexRoute
  '/missions/': typeof AppMissionsIndexRoute
  '/moderation/': typeof AppModerationIndexRoute
  '/perfil/': typeof AppPerfilIndexRoute
  '/ranking/': typeof AppRankingIndexRoute
  '/missions/new/': typeof AppMissionsNewIndexRoute
  '/moderation/$id/': typeof AppModerationIdIndexRoute
  '/missions/$id/edit/': typeof AppMissionsIdEditIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof AppIndexRoute
  '/characters': typeof AppCharactersIndexRoute
  '/missions': typeof AppMissionsIndexRoute
  '/moderation': typeof AppModerationIndexRoute
  '/perfil': typeof AppPerfilIndexRoute
  '/ranking': typeof AppRankingIndexRoute
  '/missions/new': typeof AppMissionsNewIndexRoute
  '/moderation/$id': typeof AppModerationIdIndexRoute
  '/missions/$id/edit': typeof AppMissionsIdEditIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppLayoutRouteWithChildren
  '/_app/': typeof AppIndexRoute
  '/_app/characters/': typeof AppCharactersIndexRoute
  '/_app/missions/': typeof AppMissionsIndexRoute
  '/_app/moderation/': typeof AppModerationIndexRoute
  '/_app/perfil/': typeof AppPerfilIndexRoute
  '/_app/ranking/': typeof AppRankingIndexRoute
  '/_app/missions/new/': typeof AppMissionsNewIndexRoute
  '/_app/moderation/$id/': typeof AppModerationIdIndexRoute
  '/_app/missions/$id/edit/': typeof AppMissionsIdEditIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/characters/'
    | '/missions/'
    | '/moderation/'
    | '/perfil/'
    | '/ranking/'
    | '/missions/new/'
    | '/moderation/$id/'
    | '/missions/$id/edit/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/characters'
    | '/missions'
    | '/moderation'
    | '/perfil'
    | '/ranking'
    | '/missions/new'
    | '/moderation/$id'
    | '/missions/$id/edit'
  id:
    | '__root__'
    | '/_app'
    | '/_app/'
    | '/_app/characters/'
    | '/_app/missions/'
    | '/_app/moderation/'
    | '/_app/perfil/'
    | '/_app/ranking/'
    | '/_app/missions/new/'
    | '/_app/moderation/$id/'
    | '/_app/missions/$id/edit/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppLayoutRoute: typeof AppLayoutRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/_app/characters/': {
      id: '/_app/characters/'
      path: '/characters'
      fullPath: '/characters/'
      preLoaderRoute: typeof AppCharactersIndexRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/_app/missions/': {
      id: '/_app/missions/'
      path: '/missions'
      fullPath: '/missions/'
      preLoaderRoute: typeof AppMissionsIndexRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/_app/moderation/': {
      id: '/_app/moderation/'
      path: '/moderation'
      fullPath: '/moderation/'
      preLoaderRoute: typeof AppModerationIndexRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/_app/perfil/': {
      id: '/_app/perfil/'
      path: '/perfil'
      fullPath: '/perfil/'
      preLoaderRoute: typeof AppPerfilIndexRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/_app/ranking/': {
      id: '/_app/ranking/'
      path: '/ranking'
      fullPath: '/ranking/'
      preLoaderRoute: typeof AppRankingIndexRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/_app/missions/new/': {
      id: '/_app/missions/new/'
      path: '/missions/new'
      fullPath: '/missions/new/'
      preLoaderRoute: typeof AppMissionsNewIndexRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/_app/moderation/$id/': {
      id: '/_app/moderation/$id/'
      path: '/moderation/$id'
      fullPath: '/moderation/$id/'
      preLoaderRoute: typeof AppModerationIdIndexRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/_app/missions/$id/edit/': {
      id: '/_app/missions/$id/edit/'
      path: '/missions/$id/edit'
      fullPath: '/missions/$id/edit/'
      preLoaderRoute: typeof AppMissionsIdEditIndexRouteImport
      parentRoute: typeof AppLayoutRoute
    }
  }
}

interface AppLayoutRouteChildren {
  AppIndexRoute: typeof AppIndexRoute
  AppCharactersIndexRoute: typeof AppCharactersIndexRoute
  AppMissionsIndexRoute: typeof AppMissionsIndexRoute
  AppModerationIndexRoute: typeof AppModerationIndexRoute
  AppPerfilIndexRoute: typeof AppPerfilIndexRoute
  AppRankingIndexRoute: typeof AppRankingIndexRoute
  AppMissionsNewIndexRoute: typeof AppMissionsNewIndexRoute
  AppModerationIdIndexRoute: typeof AppModerationIdIndexRoute
  AppMissionsIdEditIndexRoute: typeof AppMissionsIdEditIndexRoute
}

const AppLayoutRouteChildren: AppLayoutRouteChildren = {
  AppIndexRoute: AppIndexRoute,
  AppCharactersIndexRoute: AppCharactersIndexRoute,
  AppMissionsIndexRoute: AppMissionsIndexRoute,
  AppModerationIndexRoute: AppModerationIndexRoute,
  AppPerfilIndexRoute: AppPerfilIndexRoute,
  AppRankingIndexRoute: AppRankingIndexRoute,
  AppMissionsNewIndexRoute: AppMissionsNewIndexRoute,
  AppModerationIdIndexRoute: AppModerationIdIndexRoute,
  AppMissionsIdEditIndexRoute: AppMissionsIdEditIndexRoute,
}

const AppLayoutRouteWithChildren = AppLayoutRoute._addFileChildren(
  AppLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AppLayoutRoute: AppLayoutRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
